#---------------------------------#
#      environment configuration  #
#---------------------------------#

version: 1.0.0.{build}
install:
    - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
    - ps: (Import-PowerShellDataFile "$env:APPVEYOR_BUILD_FOLDER\PowerStigDsc.psd1").RequiredModules |
            ForEach-Object { Install-Module $PSItem.moduleName -RequiredVersion $PSItem.ModuleVersion -Repository PSGallery -Scope CurrentUser -Force }
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - git clone https://github.com/Microsoft/PowerStig.Tests
    - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\PowerStig.Tests\PowerStig.Tests.psd1"
    - ps: Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo -ExcludeTag @()

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
before_deploy:
  - ps: PowerStig.Tests\Invoke-AppveyorAfterTestTask

for:
-
  branches:
    only:
      - master

  deploy:
    - provider: Environment
      name: Test PS Gallery
      on:
        appveyor_repo_tag: true

